// Enums matching Prisma schema
export const AttendingAs = {
  PRESENTER: "PRESENTER",
  PARTICIPANT: "PARTICIPANT",
} as const

export const PresentationCategory = {
  ORAL: "ORAL",
  POSTER: "POSTER",
} as const

export const SessionType = {
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
} as const

export const CurrentStatus = {
  BACHELOR_STUDENT: "BACHELOR_STUDENT",
  MASTER_STUDENT: "MASTER_STUDENT",
  PHD_STUDENT: "PHD_STUDENT",
  RESEARCHER_PROFESSIONAL: "RESEARCHER_PROFESSIONAL",
  OTHER: "OTHER",
} as const

export const TopicPreference = {
  ENGINEERING: "ENGINEERING",
  HEALTH_SCIENCE: "HEALTH_SCIENCE",
  LIFE_SCIENCE: "LIFE_SCIENCE",
  EARTH_SCIENCE: "EARTH_SCIENCE",
  MATERIAL_SCIENCE: "MATERIAL_SCIENCE",
  SOCIAL_LAW_POLITICAL_SCIENCE: "SOCIAL_LAW_POLITICAL_SCIENCE",
  HUMANITIES: "HUMANITIES",
  SPORTS_AND_ARTS: "SPORTS_AND_ARTS",
  BUSINESS_PUBLIC_ADMINISTRATION: "BUSINESS_PUBLIC_ADMINISTRATION",
  EDUCATION: "EDUCATION",
} as const

export const DietaryPreference = {
  VEGAN: "VEGAN",
  HALAL: "HALAL",
} as const

export const Gender = {
  FEMALE: "FEMALE",
  MALE: "MALE",
} as const

export const RegistrationType = {
  ONLINE_PARTICIPANT_ONE_DAY: "ONLINE_PARTICIPANT_ONE_DAY",
  ONLINE_PARTICIPANT_TWO_DAYS: "ONLINE_PARTICIPANT_TWO_DAYS",
  OFFLINE_PARTICIPANT_ONE_DAY: "OFFLINE_PARTICIPANT_ONE_DAY",
  OFFLINE_PARTICIPANT_TWO_DAYS: "OFFLINE_PARTICIPANT_TWO_DAYS",
  PRESENTER_INDONESIA_STUDENT_ONLINE: "PRESENTER_INDONESIA_STUDENT_ONLINE",
  PRESENTER_INDONESIA_STUDENT_OFFLINE: "PRESENTER_INDONESIA_STUDENT_OFFLINE",
  PRESENTER_FOREIGNER_ONLINE: "PRESENTER_FOREIGNER_ONLINE",
  PRESENTER_FOREIGNER_OFFLINE: "PRESENTER_FOREIGNER_OFFLINE",
} as const
